### PR TITLE
ES 1.2.1 compatibility

### PR DESCRIPTION
**Pull request by truemped**
Hi, I want to try the filter but am running es 1.2.1 so while I was there I updated to code to the new(er) version. This should basically be the only necessary change for the 1.x version I guess.

### CODE REVIEW

**Comment by zealot128** [comment]
Just hijacking this PR:

Seems not to work with 1.3 versions (tested 1.3.1), during installation: 

```
bin/plugin --install analysis-file-watcher-synonym --url https://github.com/truemped/elasticsearch-analysis-file-watcher-synonym/archive/master.zip

-> Installing analysis-file-watcher-synonym...
Trying https://github.com/truemped/elasticsearch-analysis-file-watcher-synonym/archive/master.zip...
Downloading ........DONE
Installed analysis-file-watcher-synonym into /usr/share/elasticsearch/plugins/analysis-file-watcher-synonym

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

```

Any idea, how to install the plugin anyways?

**Comment by truemped** [comment]
I think you have to build locally and then install the plugin from the zip file.

**Comment by zealot128** [comment]
thx @truemped, after building it with maven, seems to work with 1.3.1, too!

**Comment by lindstromhenrik** [comment]
Merged. 
Built an updated version (0.2.0) that works with Elasticsearch 1.x (https://github.com/lindstromhenrik/elasticsearch-analysis-file-watcher-synonym/releases/).

Thanks!

**Pull request merged**
